-- MySQL Script generated by MySQL Workbench
-- Thu Feb 18 21:20:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_libreria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_libreria` DEFAULT CHARACTER SET utf8 ;
USE `bd_libreria` ;

-- -----------------------------------------------------
-- Table `bd_libreria`.`t_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_libreria`.`t_autor` (
  `autor_id` INT NOT NULL,
  `autor_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`autor_id`),
  UNIQUE INDEX `autor_id_UNIQUE` (`autor_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_libreria`.`t_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_libreria`.`t_categoria` (
  `categoria_id` INT NOT NULL,
  `categoria_descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_libreria`.`t_libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_libreria`.`t_libro` (
  `libro_id` INT NOT NULL,
  `libro_nombre` VARCHAR(45) NULL,
  `libro_cant` INT NULL,
  `libro_edición` VARCHAR(45) NULL,
  `t_autor_autor_id` INT NOT NULL,
  `t_categoria_categoria_id` INT NOT NULL,
  PRIMARY KEY (`libro_id`),
  INDEX `fk_t_libro_t_autor_idx` (`t_autor_autor_id` ASC),
  INDEX `fk_t_libro_t_categoria1_idx` (`t_categoria_categoria_id` ASC),
  CONSTRAINT `fk_t_libro_t_autor`
    FOREIGN KEY (`t_autor_autor_id`)
    REFERENCES `bd_libreria`.`t_autor` (`autor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_libro_t_categoria1`
    FOREIGN KEY (`t_categoria_categoria_id`)
    REFERENCES `bd_libreria`.`t_categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_libreria`.`t_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_libreria`.`t_usuario` (
  `usuario_id` INT NOT NULL,
  `usuario_nombre` VARCHAR(45) NULL,
  `usuario_apellido` VARCHAR(45) NULL,
  `usuario_dni` VARCHAR(8) NULL,
  `usuario_fec_nacimiento` DATE NULL,
  PRIMARY KEY (`usuario_id`),
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuario_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_libreria`.`t_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_libreria`.`t_reserva` (
  `reserva_id` INT NOT NULL,
  `reserva_fecha_inicio` DATE NULL,
  `reserva_decha_fin` DATE NULL,
  `reserva_estado` VARCHAR(45) NULL,
  `t_libro_libro_id` INT NOT NULL,
  `t_usuario_usuario_id` INT NOT NULL,
  PRIMARY KEY (`reserva_id`),
  UNIQUE INDEX `reserva_id_UNIQUE` (`reserva_id` ASC),
  INDEX `fk_t_reserva_t_libro1_idx` (`t_libro_libro_id` ASC),
  INDEX `fk_t_reserva_t_usuario1_idx` (`t_usuario_usuario_id` ASC),
  CONSTRAINT `fk_t_reserva_t_libro1`
    FOREIGN KEY (`t_libro_libro_id`)
    REFERENCES `bd_libreria`.`t_libro` (`libro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_reserva_t_usuario1`
    FOREIGN KEY (`t_usuario_usuario_id`)
    REFERENCES `bd_libreria`.`t_usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_libreria`.`t_sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_libreria`.`t_sede` (
  `sede_id` INT NOT NULL,
  `sede_ubicacion` VARCHAR(45) NULL,
  `sede_latitud` FLOAT(9,7) NULL,
  `sede_longitud` FLOAT(9,7) NULL,
  PRIMARY KEY (`sede_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_libreria`.`t_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_libreria`.`t_plan` (
  `plan_id` INT NOT NULL,
  `plan_descripcion` VARCHAR(180) NULL,
  `plan_precio` FLOAT(5,2) NULL,
  PRIMARY KEY (`plan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_libreria`.`t_menbresia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_libreria`.`t_menbresia` (
  `menbresia_id` INT NOT NULL,
  `menbresia_fech_inicio` DATE NULL,
  `menbresia_fech_fin` DATE NULL,
  `usuario_usuario_id` INT NOT NULL,
  `plan_idt_plan` INT NOT NULL,
  PRIMARY KEY (`menbresia_id`),
  INDEX `fk_t_menbresia_t_usuario1_idx` (`usuario_usuario_id` ASC),
  INDEX `fk_t_menbresia_t_plan1_idx` (`plan_idt_plan` ASC),
  CONSTRAINT `fk_t_menbresia_t_usuario1`
    FOREIGN KEY (`usuario_usuario_id`)
    REFERENCES `bd_libreria`.`t_usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_menbresia_t_plan1`
    FOREIGN KEY (`plan_idt_plan`)
    REFERENCES `bd_libreria`.`t_plan` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `bd_libreria`.`t_sede_libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_libreria`.`t_sede_libro` (
  `sede_libro_id` INT NOT NULL,
  `libro_id` INT NOT NULL,
  `t_sede_id` INT NOT NULL,
  PRIMARY KEY (`sede_libro_id`),
  INDEX `fk_t_sede_libro_t_libro1_idx` (`libro_id` ASC),
  INDEX `fk_t_sede_libro_t_sede1_idx` (`t_sede_id` ASC),
  CONSTRAINT `fk_t_sede_libro_t_libro1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `bd_libreria`.`t_libro` (`libro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_sede_libro_t_sede1`
    FOREIGN KEY (`t_sede_id`)
    REFERENCES `bd_libreria`.`t_sede` (`sede_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
